spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson

---

spring:
  profiles: dev
security:
  user:
    name: dev-user
    password: p24_DEV
    role: USER,ADMIN,ACTUATOR
