spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson
privat24:
  url: https://api.privatbank.ua/p24api
  format: json
---
spring:
  profiles: dev
security:
  user:
    name: dev-user
    password: p24_DEV
    role: USER,ADMIN,ACTUATOR
