spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson
privat24:
  url: https://api.privatbank.ua/p24api
  format: json
---
spring:
  profiles: prod
logging:
  level:
    com.voidaspect.public24: error
---
spring:
  profiles: staging
logging:
  level:
    com.voidaspect.public24: debug
---
spring:
  profiles: dev
logging:
  level:
    com.voidaspect.public24: debug
security:
  user:
    name: dev-user
    password: p24_DEV
    role: USER,ADMIN,ACTUATOR
